change to a new theme

diff --git a/bash/bash_prompt b/bash/bash_prompt
--- a/bash/bash_prompt
+++ b/bash/bash_prompt
@@ -1,149 +1,90 @@
 #!/usr/bin/env bash
+# bash_prompt: bash colors matching the vim-clean colorscheme
+# https://github.com/wonkyoc/vim-clean
+#
+#   ~/projects/personal/dotfiles  main*+          (host shown over ssh)
+#   ›                                             (red with exit code on failure)
+#
+# Variant follows vim-clean: export CLEAN_VARIANT=paper|linen|white (default paper)
+# Truecolor by default; export CLEAN_TRUECOLOR=0 for 256-color terminals.
+# Works with bash 3.2 (macOS) and bash 5 (Ubuntu).
 
-# bash_prompt
+case $- in *i*) ;; *) return 0 2>/dev/null ;; esac
 
-# Example:
-# nicolas@host: ~/.dotfiles on master [+!?$]
-# https://github.com/mathiasbynens/dotfiles/blob/master/.bash_prompt
-# $
+_clean_tc=${CLEAN_TRUECOLOR:-1}
+case $TERM in dumb|linux|vt*) _clean_tc=0 ;; esac
 
-# Screenshot: http://i.imgur.com/DSJ1G.png
-# iTerm2 prefs: import Solarized theme (disable bright colors for bold text)
-# Color ref: http://vim.wikia.com/wiki/Xterm256_color_names_for_console_Vim
-# More tips: http://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html
+_clean_palette() {
+  case ${CLEAN_VARIANT:-paper} in
+    linen)
+      if [ "$_clean_tc" = 1 ]; then _c_fg='49;19;23' _c_bg='255;252;252' _c_muted='140;122;124' _c_linenr='181;168;170' _c_nontext='210;201;202' _c_accent='156;63;34' _c_string='44;103;50' _c_const='138;90;18' _c_type='91;58;140' _c_preproc='122;82;48' _c_special='44;103;197' _c_error='186;38;35' _c_search='250;229;152' _c_visual='236;226;211'
+      else _c_fg=234 _c_bg=231 _c_muted=244 _c_linenr=248 _c_nontext=252 _c_accent=88 _c_string=65 _c_const=94 _c_type=97 _c_preproc=137 _c_special=25 _c_error=124 _c_search=222 _c_visual=254; fi ;;
+    white)
+      if [ "$_clean_tc" = 1 ]; then _c_fg='13;13;13' _c_bg='255;255;255' _c_muted='110;110;110' _c_linenr='168;168;168' _c_nontext='202;202;202' _c_accent='44;103;197' _c_string='44;103;50' _c_const='172;79;35' _c_type='100;60;174' _c_preproc='149;97;31' _c_special='31;78;148' _c_error='186;38;35' _c_search='250;229;152' _c_visual='209;229;253'
+      else _c_fg=232 _c_bg=231 _c_muted=242 _c_linenr=248 _c_nontext=251 _c_accent=25 _c_string=65 _c_const=130 _c_type=98 _c_preproc=94 _c_special=25 _c_error=124 _c_search=222 _c_visual=189; fi ;;
+    paper|*)
+      if [ "$_clean_tc" = 1 ]; then _c_fg='25;25;25' _c_bg='247;246;245' _c_muted='123;122;122' _c_linenr='167;166;166' _c_nontext='198;197;197' _c_accent='34;0;255' _c_string='44;103;50' _c_const='172;79;35' _c_type='100;60;174' _c_preproc='149;97;31' _c_special='31;78;148' _c_error='186;38;35' _c_search='250;229;152' _c_visual='226;221;246'
+      else _c_fg=234 _c_bg=255 _c_muted=243 _c_linenr=248 _c_nontext=251 _c_accent=21 _c_string=65 _c_const=130 _c_type=98 _c_preproc=94 _c_special=25 _c_error=124 _c_search=222 _c_visual=189; fi ;;
+  esac
+}
+_clean_palette
 
-prompt_git() {
-    local s=""
-    local branchName=""
-
-    # check if the current directory is in a git repository
-    if [ $(git rev-parse --is-inside-work-tree &>/dev/null; printf "%s" $?) == 0 ]; then
-
-        # check if the current directory is in .git before running git checks
-        if [ "$(git rev-parse --is-inside-git-dir 2> /dev/null)" == "false" ]; then
-
-            # ensure index is up to date
-            git update-index --really-refresh  -q &>/dev/null
-
-            # check for uncommitted changes in the index
-            if ! $(git diff --quiet --ignore-submodules --cached); then
-                s="$s+";
-            fi
-
-            # check for unstaged changes
-            if ! $(git diff-files --quiet --ignore-submodules --); then
-                s="$s!";
-            fi
-
-            # check for untracked files
-            if [ -n "$(git ls-files --others --exclude-standard)" ]; then
-                s="$s?";
-            fi
-
-            # check for stashed files
-            if $(git rev-parse --verify refs/stash &>/dev/null); then
-                s="$s$";
-            fi
-
-        fi
-
-        # get the short symbolic ref
-        # if HEAD isn't a symbolic ref, get the short SHA
-        # otherwise, just give up
-        branchName="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
-                      git rev-parse --short HEAD 2> /dev/null || \
-                      printf "(unknown)")"
-
-        [ -n "$s" ] && s=" [$s]"
-
-        printf "%s" "${1}${branchName}${2}$s"
-    else
-        return
-    fi
+# SGR sequence for a palette color: _clean_sgr 38|48 name
+_clean_sgr() {
+  local v; eval "v=\$_c_$2"
+  if [ "$_clean_tc" = 1 ]; then printf '%s;2;%s' "$1" "$v"; else printf '%s;5;%s' "$1" "$v"; fi
 }
 
-# https://www.gnu.org/software/bash/manual/html_node/Controlling-the-Prompt.html
-set_prompts() {
-    local black=""
-    local blue=""
-    local bold=""
-    local cyan=""
-    local green=""
-    local orange=""
-    local purple=""
-    local red=""
-    local reset=""
-    local white=""
-    local yellow=""
-    local violet=""
-
-    local hostStyle=""
-    local userStyle=""
-
-    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
-        tput sgr0 # reset colors
-
-        bold=$(tput bold)
-        reset=$(tput sgr0)
-
-        # Solarized colors
-        # (https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized#the-values)
-        black=$(tput setaf 0)
-        blue=$(tput setaf 33)
-        cyan=$(tput setaf 37)
-        green=$(tput setaf 64)
-        orange=$(tput setaf 166)
-        purple=$(tput setaf 125)
-        red=$(tput setaf 124)
-        white=$(tput setaf 15)
-        violet=$(tput setaf 61)
-        yellow=$(tput setaf 136)
-    else
-        bold=""
-        reset="\e[0m"
-
-        black="\e[1;30m"
-        blue="\e[1;34m"
-        cyan="\e[1;36m"
-        green="\e[1;32m"
-        orange="\e[1;33m"
-        purple="\e[1;35m"
-        red="\e[1;31m"
-        violet="\e[1;35m"
-        white="\e[1;37m"
-        yellow="\e[1;33m"
-    fi
-
-    # build the prompt
-
-    # logged in as root
-    if [[ "$USER" == "root" ]]; then
-        userStyle="$bold$red"
-        symbol="#"
-    else
-        userStyle="$orange"
-        symbol="$"
-    fi
-
-    # connected via ssh
-    if [[ "$SSH_TTY" ]]; then
-        hostStyle="$red"
-    else
-        hostStyle="$yellow"
-    fi
-
-    # set the terminal title to the current working directory
-    PS1="\[\033]0;\w\007\]"
-    PS1+="\n" # newline
-    PS1+="\[${userStyle}\]\u"; # username
-    PS1+="\[${reset}\]:";
-    PS1+="\[${hostStyle}\]\h"; # host
-    PS1+=" \[$green\]\w " # working directory
-#    PS1+="\$(prompt_git \"\[${white}\] on \[${violet}\]\" \"\[${blue}\]\")"; # git repository details
-    PS1+="\[$reset\](\[$red\]$?\[$reset\]) ${symbol} \[$reset\]" # $ (and reset color)
-
-    export PS1
+# ------------------------------------------------------------------ Prompt
+_clean_git() {
+  local b
+  b=$(git symbolic-ref --quiet --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null) || return
+  _clean_git_out="  \[\e[$(_clean_sgr 38 accent)m\]$b"
+  git diff --no-ext-diff --quiet --ignore-submodules 2>/dev/null \
+    || _clean_git_out+="\[\e[$(_clean_sgr 38 const)m\]*"
+  git diff --no-ext-diff --cached --quiet --ignore-submodules 2>/dev/null \
+    || _clean_git_out+="\[\e[$(_clean_sgr 38 string)m\]+"
 }
 
-set_prompts
-unset set_prompts
+_clean_prompt() {
+  local status=$? r='\[\e[0m\]' host='' venv='' mark
+  local ink="\[\e[1;$(_clean_sgr 38 fg)m\]" muted="\[\e[$(_clean_sgr 38 muted)m\]"
+  local dim="\[\e[$(_clean_sgr 38 linenr)m\]" err="\[\e[$(_clean_sgr 38 error)m\]"
+  _clean_git_out=''
+  _clean_git
+  [ -n "$SSH_CONNECTION" ] && host="${dim}\u@\h${r} "
+  [ -n "$VIRTUAL_ENV" ] && venv="  \[\e[$(_clean_sgr 38 type)m\]${VIRTUAL_ENV##*/}${r}"
+  [ "$EUID" = 0 ] && mark='#' || mark='›'
+  if [ "$status" = 0 ]; then mark="${muted}${mark}${r}"; else mark="${err}${status} ${mark}${r}"; fi
+  # window title, blank line, [user@host] path branch venv, then the mark
+  PS1="\[\e]0;\h: \w\a\]\n${host}${ink}\w${r}${_clean_git_out}${r}${venv}\n${mark} "
+  PS2="${muted}…${r} "
+  return $status
+}
+export VIRTUAL_ENV_DISABLE_PROMPT=1
+case ";${PROMPT_COMMAND};" in
+  *";_clean_prompt;"*) ;;
+  *) PROMPT_COMMAND="_clean_prompt${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
+esac
+
+# ---------------------------------------------------------------- ls colors
+# GNU ls (Ubuntu) reads LS_COLORS; bash_aliases skips dircolors when this is set
+export LS_COLORS="di=1;$(_clean_sgr 38 accent):ln=$(_clean_sgr 38 type):ex=$(_clean_sgr 38 string):so=$(_clean_sgr 38 preproc):pi=$(_clean_sgr 38 preproc):bd=$(_clean_sgr 38 const):cd=$(_clean_sgr 38 const):or=$(_clean_sgr 38 error):mi=$(_clean_sgr 38 error):su=$(_clean_sgr 38 error):sg=$(_clean_sgr 38 error):tw=1;$(_clean_sgr 38 accent):ow=1;$(_clean_sgr 38 accent)"
+export CLEAN_LS_COLORS=1
+export CLICOLOR=1 LSCOLORS=Exfxdxdxcxdadaeaeaeaea   # macOS ls: 8 ANSI colors only
+
+# Tab completion lists use LS_COLORS; the typed prefix is muted
+bind 'set colored-stats on' 2>/dev/null
+bind 'set colored-completion-prefix on' 2>/dev/null
+bind 'set visible-stats on' 2>/dev/null
+
+# ------------------------------------------------------------- grep, less
+export GREP_COLORS="ms=$(_clean_sgr 48 search);$(_clean_sgr 38 fg):mc=$(_clean_sgr 48 search):fn=$(_clean_sgr 38 type):ln=$(_clean_sgr 38 linenr):se=$(_clean_sgr 38 nontext)"
+# man pages: headings bold ink, emphasis in accent, status line like vim
+export LESS_TERMCAP_md=$'\e[1;'"$(_clean_sgr 38 fg)m"
+export LESS_TERMCAP_me=$'\e[0m'
+export LESS_TERMCAP_us=$'\e[4;'"$(_clean_sgr 38 accent)m"
+export LESS_TERMCAP_ue=$'\e[0m'
+export LESS_TERMCAP_so=$'\e['"$(_clean_sgr 48 fg);$(_clean_sgr 38 bg)m"
+export LESS_TERMCAP_se=$'\e[0m'
+export GROFF_NO_SGR=1   # Ubuntu man needs this for LESS_TERMCAP colors
